### ISSUE TITLE
Ways to ignore errors/warnings

### ISSUE THREAD

**Issue by ghostsquad** [salihzain/tagalyzer#4]
I might be your first star!! Found this project on reddit. ⭐

Is there a way to ignore errors/warnings?

**Comment by salihzain** [comment]
Hi @ghostsquad, thanks for being my first star! 

If I understand correctly, you'd like a way to ignore tag analysis on specific fields? 
For example: 
```go
type Person struct {
    ID int64 `tagalyzer:"-"`
    Name string `json:"name"`
    ...
}
```
In this case, the analyzer won't report a diagnostic message for missing tag json in Person.ID. 

If that's what you're looking for, then I can add it fairly easily :)

**Comment by ghostsquad** [comment]
Yep

**Comment by salihzain** [comment]
> 
> 
> Yep

Awesome, I will work on adding that as soon as I can 😎

**Comment by salihzain** [comment]
@ghostsquad 
Any notes? https://github.com/salihzain/tagalyzer/pull/5
